name = "zhongjin-shujie-wedding"
compatibility_date = "2026-08-02"
pages_build_output_dir = "."

[[d1_databases]]
binding = "WEDDING_DB"
database_name = "wedding-rsvp"
database_id = "b139a2d6-eb06-49cd-8444-6de092f773f8"
